# 事件
```js
// 如果是 IPC 衍生的，每当子进程收到父进程使用 childprocess.send() 发送的消息时，就会触发 'message' 事件
// message <Object> | <boolean> | <number> | <string> | <null> 解析的 JSON 对象或可序列化的原始值。
// sendHandle <net.Server> | <net.Socket> net.Server 或 net.Socket 对象、或未定义。
process.on("message", (message, sendHandle) => {});

// 如果 Node.js 进程是使用 IPC 通道衍生（参见子进程和集群文档），则在 IPC 通道关闭时将触发 'disconnect' 事件。
process.on("disconnect", () => {});

// 'unhandledRejection' 事件对于检测和跟踪尚未处理的被拒绝的 promise 很有用。
// 每当 Promise 被拒绝并且在事件循环的一个轮询内没有错误句柄附加到承诺时，则会触发 'unhandledRejection' 事件。 使用 Promise 进行编程时，异常被封装为“被拒绝的 promise”。
process.on("unhandledRejection", () => {});

// 当 Node.js 触发进程警告时，则会触发 'warning' 事件
// Node.js 可以在检测到可能导致次优应用程序性能、错误或安全漏洞的不良编码实践时触发警告。
process.on("warning", (name, message, stack) => {});

// 异常没有捕获， 默认情况下，Node.js 通过将堆栈跟踪打印到 stderr 并以代码 1 退出，覆盖任何先前设置的 process.exitCode 来处理此类异常。
// 为 'uncaughtException' 事件添加处理会覆盖此默认行为。 或者，更改 'uncaughtException' 处理程序中的 process.exitCode，这将导致进程以提供的退出码退出。 否则，在存在此类句柄的情况下，进程将以 0 退出。
// err <Error> 未捕获的异常。
// origin：指示异常是源自未处理的拒绝还是源自同步错误
process.on("uncaughtException", (error, origin) => {});

// 'uncaughtExceptionMonitor' 事件在 'uncaughtException' 事件、或通过 process.setUncaughtExceptionCaptureCallback() 安装的钩子被调用之前触发。
// 一旦触发 'uncaughtException' 事件，则安装 'uncaughtExceptionMonitor' 监听器不会更改行为。 如果没有安装 'uncaughtException' 监听器，则进程仍然会崩溃。
process.on("uncaughtExceptionMonitor", (error, origin) => {});

// 晚于 uncaughtException ，先由其处理 但在处理过程中获得了拒绝句柄。 然后 晚于一轮 Node.js 事件循环时， rejectionHandled 处理
process.on("rejectionHandled", (promise) => {});

// 多个解决、拒绝时候的事件
// type <string> 解决类型 'resolve' 或 'reject' 之一。
// promise <Promise> 不止一次解决或拒绝的 promise。
// value <any> 在原始解决之后解决或拒绝 promise 的值。
// Promise 满足以下任一条件时，就会触发 'multipleResolves' 事件：
// 解决了不止一次。
// 拒绝了不止一次。
// 解决后拒绝。
// 拒绝后解决。
// 例如：
// return await new Promise((resolve, reject) => {
//     resolve('First call');
//     resolve('Swallowed resolve');
//     reject(new Error('Swallowed reject'));
// });
process.on("multipleResolves", (type, promise, value) => {});

// 当 Node.js 清空其事件循环并且没有额外的工作要安排时，则会触发 'beforeExit' 事件。 通常情况下，当没有工作要调度时，Node.js 进程会退出，但是注册在 'beforeExit' 事件上的监听器可以进行异步的调用，从而使 Node.js 进程继续。
// 对于导致显式终止的条件，例如调用 process.exit() 或未捕获的异常，则不会触发 'beforeExit' 事件。
process.on("beforeExit", (code) => {});

// process.exit() 方法被显式调用；
// Node.js 事件循环不再需要执行任何额外的工作。
// exit 中只能执行同步函数
// 一旦所有 'exit' 监听器都运行完毕，则 Node.js 进程将终止
process.on("exit", (code) => {});

// 信号事件
// 'SIGUSR1' 由 Node.js 预留以启动调试器。 可以安装监听器，但这样做可能会干扰调试器。
// 'SIGTERM' 和 'SIGINT' 在非 Windows 平台上具有默认的句柄，其在使用代码 128 + signal number 退出之前重置终端模式。 如果这些信号之一安装了监听器，则其默认行为将被删除（Node.js 将不再退出）。
// 'SIGPIPE' 默认情况下忽略。 它可以安装监听器。
// 'SIGHUP' 在 Windows 上是在关闭控制台窗口时生成，在其他平台上是在各种类似条件下生成。 参见 signal(7)。 它可以安装监听器，但是 Node.js 将在大约 10 秒后被 Windows 无条件地终止。 在非 Windows 平台上，SIGHUP 的默认行为是终止 Node.js，但一旦安装了监听器，则其默认行为将被删除。
// 'SIGTERM' Windows 上不支持，可以监听。所有平台都支持来自终端的 'SIGINT'，通常可以使用 Ctrl+C 生成（但是这是可配置的）。 当启用终端原始模式并使用 Ctrl+C 时不会生成它。
// 'SIGBREAK' 在 Windows 上，当按下 Ctrl+Break 时会发送。 在非 Windows 平台上，它可以被监听，但无法发送或生成它。
// 'SIGWINCH' 当调整控制台大小时会发送。 在 Windows 上，这只会发生在当光标移动时写入控制台，或者当在原始模式下使用可读的终端时。
// 'SIGKILL' 不能安装监听器，它会无条件地终止所有平台上的 Node.js。
// 'SIGSTOP' 不能安装监听器。
// 'SIGBUS', 'SIGFPE', 'SIGSEGV', and 'SIGILL' 当没有使用kill(2)人为地引发时，必然会让进程处于一种调用JS侦听器不安全的状态。这样做可能会导致进程停止响应
// 发送信号 0 可以作为独立于平台的方式来测试进程是否存在。
process.on("SIGINT", () => {});
process.on("SIGTERM", () => {});
```
